apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-build-workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    # If you have a private repo or special restrictions, you might still need:
    # permissions:
    #   scm-token-own: read
    #   scm-token-org: read

    steps:
      - name: Clone code
        # Use Alpine Git container to clone code, similar to your Django example
        uses: docker://alpine/git
        shell: sh
        run: |
          # Clone OWASP Juice Shop from GitHub (public example)
          git clone https://github.com/juice-shop/juice-shop.git .
          # If you want to clone your own fork or private repo, 
          # replace the URL and possibly add credentials.

      - name: Install Node modules
        # Use official Node image to run 'npm install'
        uses: docker://node:16
        shell: sh
        run: |
          npm install

      - name: Build the app
        # Use the same Node image to build
        uses: docker://node:16
        shell: sh
        run: |
          npm run build
