apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-scan-workflow

on:
  push:
    branches:
      - '**'

jobs:
  scan:
    # 1) **Add permissions** so pipeline can fetch external actions from GitHub
    permissions:
      scm-token-own: read
    #   or if your repo is in an org, try:  scm-token-org: read

    steps:
      # 2) Check out your repository
      - name: Checkout repository
        uses: https://github.com/cloudbees-io/checkout@v1

      # 3) Run Gitleaks (hardcoded creds)
      - name: Gitleaks secret scan
        uses: https://github.com/cloudbees-io/gitleaks-secret-scan-code@v1

      # 4) Run Njsscan SAST for Node code
      - name: Njsscan (Node.js SAST)
        uses: https://github.com/cloudbees-io/njsscan-sast-scan-code@v1

      # 5) Run TruffleHog (another secrets scanner)
      - name: TruffleHog secret scan
        uses: https://github.com/cloudbees-io/trufflehog-secret-scan-code@v1
        # (Optional) 'with' inputs if you want to configure thresholds, etc.
        # e.g. threshold-very-high: 3

      # 6) Run Retire.js (SCA for Node/JS libs)
      - name: Retire.js SCA
        uses: https://github.com/cloudbees-io/retirejs-sca-scan-code@v1
        # (Optional) 'with' inputs if you'd like to exclude directories, etc.
