apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-scan-workflow

on:
  push:
    branches:
      - '**'

jobs:
  scan:
    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: https://github.com/cloudbees-io/checkout@v1

      # 2. Run Gitleaks (hardcoded creds)
      - name: Gitleaks secret scan
        uses: https://github.com/cloudbees-io/gitleaks-secret-scan-code@v1

      # 3. Run Njsscan SAST for Node code
      - name: Njsscan (Node.js SAST)
        uses: https://github.com/cloudbees-io/njsscan-sast-scan-code@v1

      # 4. Run TruffleHog (another secrets scanner)
      - name: TruffleHog secret scan
        uses: https://github.com/cloudbees-io/trufflehog-secret-scan-code@v1
        # (Optional) 'with' inputs if you want to configure thresholds or branch
        # e.g. threshold-very-high: 3, etc.

      # 5. Run Retire.js (SCA for Node/JS libs)
      - name: Retire.js SCA
        uses: https://github.com/cloudbees-io/retirejs-sca-scan-code@v1
        # (Optional) 'with' inputs if you'd like to exclude directories, etc.2
