apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-build-and-scan

on:
  push:
    branches:
      - '**'

jobs:
  build-and-scan:
    steps:
      # 1) Clone from https://github.com/jalts-808/juice
      - name: Clone code
        uses: docker://alpine/git:2.36.3
        shell: sh
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          git clone https://github.com/jalts-808/juice.git .

      # 2) Install Node modules
      - name: Install Node modules
        uses: docker://node:16.19.1
        shell: sh
        run: |
          npm install

      # 3) Build the app (if your package.json has 'build:frontend')
      - name: Build the app
        uses: docker://node:16.19.1
        shell: sh
        run: |
          npm run build:frontend
          # If you don't have 'build:frontend', use whatever script is in your package.json, e.g. 'npm run build'

      # 4) Gitleaks (simple secret scanner)
      - name: Gitleaks
        uses: docker://zricethezav/gitleaks:v8.17.0
        shell: sh
        run: |
          gitleaks detect --exit-code 0 --redact

      # 5) TruffleHog (another secret scanner)
      - name: TruffleHog
        uses: docker://trufflesecurity/trufflehog:3.12.0
        shell: sh
        run: |
          trufflehog filesystem --no-update . || true
