apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-demo-workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Build Docker image
        uses: docker://docker:24
        shell: sh
        run: |
          docker build -t juice:latest .
