apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-build-workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      # 1) Clone code (using alpine/git)
      - name: Clone code
        uses: docker://alpine/git
        shell: sh
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          git clone https://github.com/juice-shop/juice-shop.git .
          # If you have a private fork, replace the URL and add credentials as needed

      # 2) Install Node modules (using node Docker image)
      - name: Install Node modules
        uses: docker://node:16
        shell: sh
        run: |
          npm install

      # 3) Build with correct script (npm run build:frontend)
      - name: Build the app
        uses: docker://node:16
        shell: sh
        run: |
          npm run build:frontend
