apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-scan-workflow

on:
  push:
    branches:
      - '**'

jobs:
  scan:
    # Permissions from the docs: grants ephemeral tokens for user AND org repos
    permissions:
      scm-token-own: read
      scm-token-org: read

    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Run Gitleaks secret scan
        uses: https://github.com/cloudbees-io/gitleaks-secret-scan-code@v1

      - name: Njsscan SAST
        uses: https://github.com/cloudbees-io/njsscan-sast-scan-code@v1

      - name: TruffleHog secret scan
        uses: https://github.com/cloudbees-io/trufflehog-secret-scan-code@v1

      - name: Retire.js SCA
        uses: https://github.com/cloudbees-io/retirejs-sca-scan-code@v1
