apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-demo-workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      # 1) Check out the source code
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      # 2) Log in to Docker Hub so Kaniko can push
      #    Provide your DockerHub credentials here. 
      #    'registry' is the Docker Hub registry URL. 
      - name: Configure Docker credentials
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        with:
          registry: "https://index.docker.io/v1/"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3) Use the official Kaniko container image as a Docker step
      #    Must specify 'entrypoint' and 'args', since we do not have 'run'.
      - name: Build and push Docker image with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:latest
        with:
          entrypoint: /kaniko/executor
          args: |
            --context=.
            --dockerfile=Dockerfile
            --destination=docker.io/jamesalts/juicehub:latest
