apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-demo-workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Build and push Docker image with Kaniko
        uses: https://github.com/cloudbees-io/kaniko@v1
        with:
          # Destination image on Docker Hub. Adjust if you have credentials or need a private repo.
          destination: "docker.io/jalts-808/juice:latest"
